services:
  plex-discord-rpc:
    build: .
    # image: plex-discord-rpc
    container_name: plex-discord-rpc
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - /run/user/1000/discord-ipc-0:/tmp/discord-ipc-0:ro
      - ./plex_rpc.log:/app/plex_rpc.log
      - ./config.json:/app/config.json